services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always
    networks:
      - backend
  kurento-media-server:
    image: kurento/kurento-media-server:latest
    container_name: kurento-media-server
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
    networks:
      - backend

networks:
  backend: